name: Release

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.ref_name }}
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    release:
        name: Upload artifact
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
                with:
                    fetch-depth: 0
            
            -   name: Set up JDK 25
                uses: actions/setup-java@v5
                with:
                    distribution: temurin
                    java-version: '25'
                    cache: maven
            
            -   name: Get project version
                uses: PERES-Richard/maven-get-version-action@v3.0.0
                id: project-version
                with:
                    args: "" # default value is set to '.' which lead to wrong command
            
            -   name: Build package
                run: mvn -B -ntp package
                
            -   name: Upload ZIP artifact
                uses: actions/upload-artifact@v7
                with:
                    name: peppol-box-transmitter-${{ steps.project-version.outputs.version }}-zip
                    path: target/*.zip
                    if-no-files-found: error
                    compression-level: 0
